### ISSUE TITLE
Tesseract500.Alpha.20200328.tar.gz does not download!

### ISSUE THREAD

**Issue by ahhs72** [SubtitleEdit/support-files#3]
Hello, I'm trying to download this file and it gives me an error.

Attached image of the error:

<img width="821" alt="Captura de pantalla 2024-03-16 173215" src="https://github.com/SubtitleEdit/support-files/assets/163668519/34f75581-83b6-480f-aa12-0d1d8c73bc35">

Thanks in advance

**Comment by niksedk** [comment]
Try latest version of SE

**Comment by ahhs72** [comment]
I don't use the latest version because it loads video preview windows and they can't be disabled and they are very intrusive and annoying.

Is there no link where I can download the file?

**Comment by niksedk** [comment]
You can turn off auto-load video:
![image](https://github.com/SubtitleEdit/support-files/assets/1261331/d0b3de23-613c-454e-a1ec-6b9908913caf)


And use a layout without video:
![image](https://github.com/SubtitleEdit/support-files/assets/1261331/8bd995c8-cb7b-422e-94c1-59b65f5f7a7b)
